import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { Analytics } from "@vercel/analytics/react";
import NextAuthSessionProvider from "../providers/SessionProvider";
import { Hanken_Grotesk } from "next/font/google";
import Header from "../components/Header";

const inter = Inter({ subsets: ["latin"] });

const hkgrotestk = Hanken_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable} ${GeistMono.variable} bg-black text-white`}
    >
      <body className={`${hkgrotestk.className}`}>
        <NextAuthSessionProvider>
          <Header />
          {children}
          <Analytics />
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
